# Generated by Django 4.1 on 2022-08-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_identifiant_alter_newuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='identifiant',
        ),
        migrations.AddField(
            model_name='newuser',
            name='identifier',
            field=models.CharField(default='admin1', max_length=100, unique=True, verbose_name='identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='department',
            field=models.CharField(blank=True, max_length=250, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='institut',
            field=models.CharField(max_length=250, verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is this an active account ?'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is this a staff member ?'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the last login'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of joining'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
    ]
